export const CARD_WIDTH_CLASS = "w-[400px] mx-auto";

export const views = {
  SIGN_IN_OR_UP: "SIGN_IN_OR_UP",
  MAGIC_VERIFYING: "MAGIC_VERIFYING",
  WEBAUTHN_REGISTER: "WEBAUTHN_REGISTER",
  WEBAUTHN_VERIFY: "WEBAUTHN_VERIFY",
  MAGIC_PENDING: "MAGIC_PENDING",
  OTP_PENDING: "OTP_PENDING",
};

export const appStates = {
  LOADING: "LOADING",
  ERROR: "ERROR",
  READY: "READY",
};
